import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

const base = "https://www.veloracelace.com";
const path = "/custom-multicolor-embroidered-lace";
const whatsapp = "https://wa.me/8615767956637?text=Hello%20VELORACE%20LACE%2C%20I%20need%20custom%20multicolor%20embroidered%20lace%20trim.%20I%20will%20send%20my%20reference%20image%2C%20colors%2C%20target%20width%2C%20quantity%20and%20application.%20Please%20advise%20the%20sample%20development%20route%20and%20MOQ.";
const concepts = [
  ["/products/hair-bow-lace/pink-christmas-tree-gift-bow-embroidered-lace-trim.webp","Pink Christmas Tree + Gift + Bow","multicolor Christmas embroidered lace trim design concept with pink tree gift and bow motifs","/hair-bow-lace/pink-christmas-tree-gift-bow-embroidered-lace-trim"],
  ["/products/hair-bow-lace/ghost-pumpkin-pink-bow-embroidered-lace-trim.webp","Ghost + Pumpkin + Pink Bow","custom multicolor Halloween embroidered lace trim design concept with ghost pumpkin and pink bow motifs","/hair-bow-lace/ghost-pumpkin-pink-bow-embroidered-lace-trim"],
  ["/products/hair-bow-lace/apple-pencil-bow-embroidered-lace-trim.webp","Apple + Pencil + Bow","back-to-school multicolor embroidered lace trim concept with apple pencil and bow motifs","/hair-bow-lace/apple-pencil-bow-embroidered-lace-trim"],
  ["/products/hair-bow-lace/books-apple-school-bow-embroidered-lace-trim.webp","Books + Apple + School Bow","colorful embroidered tulle lace trim design concept for children's hair bows with books apple and school bow motifs","/hair-bow-lace/books-apple-school-bow-embroidered-lace-trim"],
] as const;

export const metadata: Metadata = {
  title: "Custom Multicolor Embroidered Lace Trim Supplier",
  description: "Develop custom multicolor embroidered lace trim from artwork or reference images. Specify thread colors, motif, repeat, width, mesh base and application for sample review.",
  alternates: { canonical: path },
  openGraph: { title: "Custom Multicolor Embroidered Lace Trim | VELORACE LACE", description: "Custom multicolor embroidery development for fashion trims, hair bows, childrenswear, seasonal collections and garment accessories.", url: path, type: "website", images: [{ url: concepts[0][0], alt: concepts[0][2] }] },
};

const faqs = [
  ["Can you develop lace with several thread colors in one design?", "Yes. Send the target color palette or reference image. The practical thread-color count, stitch plan and construction are reviewed during development before a physical sample is approved."],
  ["Can you make a custom embroidered motif from my picture or artwork?", "Send the artwork, reference photo or concept together with the intended application. We review motif scale, repeat, base material, edge construction and embroidery feasibility before sampling."],
  ["What information is useful for a multicolor lace quotation?", "Send the reference image, desired colors, finished width, estimated quantity, application and delivery country. If you have Pantone references or a physical swatch, include them for color discussion."],
  ["Can I approve a sample before bulk production?", "Yes. Sampling is the recommended step for custom multicolor designs because thread colors, motif scale, mesh, stitch density and repeat should be checked on a physical sample before bulk production."],
  ["What products can use multicolor embroidered lace trim?", "Typical development briefs include children's hair bows, childrenswear, dresses, fashion accessories, seasonal trims and decorative garment applications. The motif scale, width and repeat should be developed around the final product."],
  ["What should a buyer send first?", "Start with a reference image or artwork, target color palette, intended application, approximate width, estimated quantity and delivery country. These inputs make the first feasibility and sampling discussion more useful."],
] as const;

export default function MulticolorEmbroideredLacePage() {
  const schema = [
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: base }, { "@type": "ListItem", position: 2, name: "Custom Multicolor Embroidered Lace", item: `${base}${path}` }]},
    { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([q,a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) },
  ];

  return <main className="mx-auto max-w-6xl px-5 py-10 md:py-16">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <nav className="mb-6 text-sm text-neutral-600"><Link href="/">Home</Link> / Custom Multicolor Embroidered Lace</nav>
    <section className="max-w-4xl"><p className="mb-3 text-sm font-semibold uppercase tracking-wider">Custom embroidery development · Multicolor motif specialist</p><h1 className="text-4xl font-semibold leading-tight md:text-6xl">Custom Multicolor Embroidered Lace Trim</h1><p className="mt-6 text-lg leading-8 text-neutral-700">VELORACE LACE develops colorful embroidered lace and narrow lace trim around buyer artwork, reference motifs, seasonal palettes and final-product requirements. This service is intended for buyers who need more than standard white or single-color lace: send a reference and define the thread colors, motif scale, mesh base, width, repeat spacing and edge construction for sample review.</p><div className="mt-7 flex flex-wrap gap-3"><a className="rounded-full bg-black px-6 py-3 text-white" href={whatsapp}>Send a design for development</a><Link className="rounded-full border border-neutral-300 px-6 py-3" href="/embroidery-lace">Browse embroidery lace</Link></div></section>

    <section className="mt-12 rounded-2xl border border-neutral-200 p-7 md:p-9"><p className="text-sm font-semibold uppercase tracking-wider">Buyer answer</p><h2 className="mt-2 text-2xl font-semibold">Who should use this custom lace service?</h2><p className="mt-4 leading-7 text-neutral-700">Use this service when the color combination and motif are central to the product: for example, a seasonal embroidered trim, a children&apos;s hair-bow overlay, a colorful fashion edge, a branded motif or a collection that must coordinate with a defined palette. Instead of selecting only from standard lace, the buyer starts with the intended product and develops the embroidery around it.</p></section>

    <section className="mt-16"><h2 className="text-3xl font-semibold">Multicolor embroidery design directions</h2><p className="mt-4 max-w-4xl leading-7 text-neutral-700">The examples below are design concepts for custom development, not factory photographs, QC photographs or customer orders. They show how multiple thread colors and recognizable motifs can be organized for narrow embroidered trim. Final colors, dimensions, construction and repeat are confirmed through sample review.</p><div className="mt-7 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{concepts.map(([src,title,alt,href]) => <Link href={href} key={src} className="overflow-hidden rounded-2xl border border-neutral-200"><Image src={src} alt={alt} width={900} height={900} sizes="(min-width: 1024px) 25vw, (min-width: 768px) 50vw, 100vw" className="aspect-square w-full object-cover" /><div className="p-5"><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-neutral-600">Design concept for custom multicolor embroidery development.</p></div></Link>)}</div></section>

    <section className="mt-16"><h2 className="text-3xl font-semibold">What can be customized?</h2><div className="mt-7 grid gap-4 md:grid-cols-3">{[["Multicolor thread palette","Develop several coordinated embroidery colors in one motif. Send Pantone references, a swatch or a visual palette for review."],["Motif & repeat","Develop floral, bow, seasonal, school, faith, novelty or brand-specific directions from artwork and reference images."],["Base & construction","Discuss tulle or mesh base, trim width, scalloped edges, motif spacing and construction according to the final application."],["Seasonal collections","Build coordinated Christmas, Halloween, back-to-school, Valentine's and other seasonal embroidery directions."],["Application fit","Adjust scale and repeat for hair bows, childrenswear, dresses, fashion accessories and decorative garment trims."],["Physical sampling","Approve color balance, stitch definition, scale and hand feel on a physical sample before confirming bulk production."]].map(([h,p]) => <article className="rounded-2xl border border-neutral-200 p-6" key={h}><h3 className="text-xl font-semibold">{h}</h3><p className="mt-3 leading-7 text-neutral-700">{p}</p></article>)}</div></section>

    <section className="mt-16 rounded-2xl bg-neutral-100 p-7 md:p-10"><p className="text-sm font-semibold uppercase tracking-wider">Procurement workflow</p><h2 className="mt-2 text-3xl font-semibold">From buyer artwork to approved embroidered lace sample</h2><p className="mt-4 max-w-4xl leading-7 text-neutral-700">A custom lace project is easier to quote and repeat when the artwork, embroidery construction and physical approval reference are treated as separate steps. The exact digitising, sampling, MOQ, price and lead time are confirmed for the selected design rather than assumed in advance.</p><ol className="mt-7 grid gap-5 md:grid-cols-5"><li><strong>1. Send artwork</strong><p className="mt-2 text-neutral-700">Reference image, vector artwork or product photo plus intended application.</p></li><li><strong>2. Plan colors & construction</strong><p className="mt-2 text-neutral-700">Review thread palette, base, width, motif scale, repeat and edge direction.</p></li><li><strong>3. Digitising review</strong><p className="mt-2 text-neutral-700">Translate the approved motif direction into a practical embroidery route and confirm the sample scope.</p></li><li><strong>4. Strike-off / sample</strong><p className="mt-2 text-neutral-700">Produce a physical development sample to check color balance, stitch definition, scale and hand feel.</p></li><li><strong>5. Approve for bulk</strong><p className="mt-2 text-neutral-700">Confirm the written specification and physical reference before bulk production terms are finalized.</p></li></ol></section>

    <section className="mt-16"><h2 className="text-3xl font-semibold">What to send for a faster sourcing discussion</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><article className="rounded-2xl border border-neutral-200 p-6"><h3 className="text-xl font-semibold">Design information</h3><p className="mt-3 leading-7 text-neutral-700">Reference image or artwork, target colors, approximate finished width, motif size or desired visual scale, repeat preference, base material and edge direction.</p></article><article className="rounded-2xl border border-neutral-200 p-6"><h3 className="text-xl font-semibold">Commercial information</h3><p className="mt-3 leading-7 text-neutral-700">Intended application, estimated quantity, sample requirement, destination country and target delivery window. MOQ, price and production timing should be confirmed for the selected construction rather than assumed from another design.</p></article></div></section>

    <section className="mt-16 grid gap-8 md:grid-cols-2"><div><h2 className="text-3xl font-semibold">Especially suitable for colorful narrow trims</h2><p className="mt-4 leading-7 text-neutral-700">Our current development direction includes multicolor embroidered tulle trim for children&apos;s boutique hair bows and seasonal accessories. These concepts demonstrate how coordinated thread colors, recognizable motifs and repeating narrow-trim layouts can be developed around a specific market and finished product.</p><div className="mt-5 flex flex-wrap gap-5"><Link className="font-semibold underline" href="/hair-bow-lace">Explore the Hair Bow Lace Collection</Link><Link className="font-semibold underline" href="/seasonal-embroidered-lace-trim">Explore Seasonal Embroidered Lace</Link></div></div><div><h2 className="text-3xl font-semibold">Also sourcing bridal embroidery?</h2><p className="mt-4 leading-7 text-neutral-700">For softer ivory and tonal embroidery used on wedding gowns, veils and bodices, use the dedicated bridal sourcing pages instead of mixing that intent with colorful fashion trim.</p><Link className="mt-5 inline-block font-semibold underline" href="/bridal-lace/embroidered-tulle">Fine Embroidered Tulle Bridal Lace</Link></div></section>

    <section className="mt-16"><h2 className="text-3xl font-semibold">Custom multicolor embroidered lace FAQ</h2><div className="mt-6 divide-y">{faqs.map(([q,a]) => <div className="py-5" key={q}><h3 className="text-xl font-semibold">{q}</h3><p className="mt-2 leading-7 text-neutral-700">{a}</p></div>)}</div></section>
    <section className="mt-16 rounded-2xl bg-black p-8 text-white md:p-10"><p className="text-sm font-semibold uppercase tracking-wider">Start with your design</p><h2 className="mt-3 text-3xl font-semibold">Need several colors in one embroidered lace trim?</h2><p className="mt-4 max-w-3xl leading-7 text-neutral-200">Send the reference, target colors, width, quantity, application and destination. We will use those details to discuss the appropriate development and sampling route without assuming unconfirmed production specifications.</p><a className="mt-6 inline-block rounded-full bg-white px-6 py-3 font-semibold text-black" href={whatsapp}>Send reference on WhatsApp</a></section>
  </main>;
}
