import { notFound } from "next/navigation";
import { HairBowBreadcrumb, HairBowCards, HairBowCTA, HairBowFAQ, HairBowImage } from "@/components/HairBowLace";
import { conceptNotice, designFaq, hairBowDesigns, hairBowPath, hairBowUrl, orderingAnswer } from "@/lib/hair-bow-lace";
import { absoluteUrl, createPageMetadata } from "@/lib/seo";

export const dynamicParams = false;
export function generateStaticParams() { return hairBowDesigns.map(({ slug }) => ({ slug })); }
export function generateMetadata({ params }: { params: { slug: string } }) {
  const design = hairBowDesigns.find(item => item.slug === params.slug);
  if (!design) notFound();
  return createPageMetadata(`${design.name} Lace Trim`, `${design.name} embroidered tulle lace concept for US boutique hair bows. Target 1.5 inch width; discuss custom colors, sampling and ordering.`, hairBowUrl(design), design.image);
}
export default function HairBowProduct({ params }: { params: { slug: string } }) {
  const design = hairBowDesigns.find(item => item.slug === params.slug);
  if (!design) notFound();
  const related = [...hairBowDesigns.filter(item => item.theme === design.theme && item !== design), ...hairBowDesigns.filter(item => item.theme !== design.theme)].slice(0, 3);
  const webPage = { "@context": "https://schema.org", "@type": "WebPage", "@id": `${absoluteUrl(hairBowUrl(design))}#webpage`, name: `${design.name} Embroidered Lace Trim`, description: `${design.description} Design concept for US boutique hair bow development; target width approximately 1.5 inches, subject to sample approval.`, url: absoluteUrl(hairBowUrl(design)), ...(design.image ? { primaryImageOfPage: { "@type": "ImageObject", url: absoluteUrl(design.image) } } : {}), audience: { "@type": "BusinessAudience", audienceType: "US boutique hair bow brands, hair accessory designers and bow supply buyers" }, about: { "@type": "Thing", name: "Custom embroidered tulle lace trim design concept" } };
  return <main className="bow-page"><HairBowBreadcrumb design={design} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(webPage) }} /><section className="bow-product-hero"><figure><HairBowImage design={design} priority /><figcaption>{conceptNotice}</figcaption></figure><div><p className="eyebrow">VELORACE LACE · {design.theme}</p><h1>{design.name} Embroidered Lace Trim</h1><p className="bow-lead">Hair bow lace overlay · 1.5 inch development target</p><p>{design.description}</p><p>Developed as a decorative overlay concept for {design.use.toLowerCase()}. This is a trim inquiry, not a finished bow purchase.</p><HairBowCTA design={design} placement="hair_bow_product_hero" /></div></section><section className="bow-guide"><h2>Using this design for children&apos;s hair bows</h2><p>Lay the lace over your selected ribbon and position the motif repeat on the bow loops. Check how folding, cutting and the center wrap affect the visible design. Test your chosen attachment method with the physical sample.</p><p>{design.development}</p><h2>Customization and sample development</h2><p>Share desired thread colors, mesh base, edge finish, repeat spacing and width. Approximately 1.5 inches (38.1 mm) is the target for review; final measurements and compatibility with your backing ribbon must be confirmed on the sample.</p><p>Agree the development specification and sample scope before sampling. Approve the physical sample before confirming bulk production.</p><h2>Ordering information</h2><p>{orderingAnswer}</p><dl className="bow-specs"><div><dt>Product type</dt><dd>Custom embroidered tulle lace trim concept</dd></div><div><dt>Intended application</dt><dd>{design.use}</dd></div><div><dt>Order unit</dt><dd>Discuss yards or meters; confirmed with quotation</dd></div><div><dt>MOQ, price and timing</dt><dd>Contact us — confirmed after design review</dd></div></dl><p>Compare the full <a href={hairBowPath}>Hair Bow Lace Collection</a> or read about <a href="/custom-design">custom design development</a>.</p></section><HairBowFAQ items={designFaq(design)} /><section><h2>Related hair bow lace concepts</h2><HairBowCards designs={related} /></section><section className="bow-inquiry"><h2>Request a design review</h2><p>Reference this design name and share your ribbon width, colors, quantity and destination.</p><HairBowCTA design={design} placement="hair_bow_product_bottom" /></section></main>;
}

