import { FeaturedHairBowLace } from "@/components/HairBowLace";
import Image from "next/image";
import { ArrowRight, BadgeCheck, Boxes, Factory, Globe2, Lightbulb, PackageCheck, Palette, SearchCheck, Sparkles, SwatchBook, Truck } from "lucide-react";
import QuoteForm from "@/components/QuoteForm";
import WhatsAppLink from "@/components/WhatsAppLink";
import { mediaUrl } from "@/lib/media";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata(
  "Custom Multicolor Embroidered Lace Supplier | VELORACE LACE",
  "Custom multicolor embroidered lace trim supplier in China for colorful motifs, seasonal designs, hair bows, fashion trims and bridal lace. Develop colors, motifs and samples from your reference.",
  "/",
  "/images/about/about-hero.webp",
);

const trust = [["Multicolor", "Several thread colors in one embroidered design"],["Custom", "Motif, color, width and repeat development"],["Flexible", "MOQ reviewed by design and process"],["Worldwide", "Export packing and shipping support"]] as const;
const homeWhatsAppMessage = "Hello VELORACE LACE, I need custom multicolor embroidered lace. I will send my reference image, colors, target width, quantity and application. Please advise the sample development route and MOQ.";
const trends = [
  { name: "Custom Multicolor Embroidery", type: "Core capability", href: "/custom-multicolor-embroidered-lace", image: "/products/embroidered-lace/embroidered-lace-butterfly.webp", alt: "custom multicolor embroidered lace trim with colorful thread motifs" },
  { name: "3D Floral Appliqué", type: "Dimensional", href: "/3d-flower-applique", image: "/products/home-ranges/3d-floral.webp", alt: "3D floral lace applique from China for bridal and couture development" },
  { name: "Beaded & Pearl Motif", type: "Hand-finished", href: "/bridal-lace", image: "/products/home-ranges/bead-rhinestone.webp", alt: "wholesale beaded bridal lace and pearl embroidery motif" },
  { name: "Embroidery Appliqué", type: "Couture", href: "/embroidery-lace", image: "/products/home-ranges/embroidery-appliques.webp", alt: "custom embroidered lace applique supplier China" },
  { name: "Butterfly Mesh Lace", type: "Multicolor", href: "/custom-multicolor-embroidered-lace", image: "/products/embroidered-lace/embroidered-lace-butterfly.webp", alt: "pastel multicolor butterfly embroidered mesh lace" },
  { name: "Gold Floral Lace", type: "Metallic", href: "/embroidery-lace", image: "/products/embroidered-lace/embroidered-lace-gold-floral.webp", alt: "gold floral embroidered lace trim" },
  { name: "Aqua Floral Lace", type: "Color trend", href: "/embroidery-lace", image: "/products/embroidered-lace/embroidered-lace-aqua-floral.webp", alt: "aqua floral embroidered lace trim" },
  { name: "Blush Floral Lace", type: "Fashion color", href: "/embroidery-lace", image: "/products/embroidered-lace/embroidered-lace-blush-floral.webp", alt: "blush pink floral embroidered lace" },
] as const;
const manufacturingProcess = [["01","Requirement Review",SearchCheck,"Application, colors, dimensions, quantity and target finish are confirmed."],["02","Motif & Color Plan",Palette,"Thread palette, base, motif scale, repeat and embroidery construction are reviewed."],["03","Sample Development",Sparkles,"A physical embroidery sample or color reference is prepared for approval."],["04","Production",Factory,"Production follows the approved reference and confirmed order details."],["05","Quality Inspection",PackageCheck,"Workmanship, color, dimensions and decorative details are reviewed."],["06","Packing & Delivery",Truck,"Export packing and international shipping are coordinated for the destination."]] as const;
const applications = [
  { title:"Hair Bows & Kids Accessories", text:"Colorful narrow embroidered trims with seasonal, novelty, bow and character-inspired motifs for boutique accessories.", image:mediaUrl("pastel-collection.jpg"), alt:"colorful embroidered lace motifs for hair bows and kids accessories" },
  { title:"Fashion Apparel", text:"Custom multicolor embroidery trims for dresses, tops, childrenswear, dancewear and designer garments.", image:mediaUrl("yellow-floral.jpg"), alt:"multicolor floral embroidered lace trim for fashion apparel" },
  { title:"Bridal & Wedding", text:"Fine bridal lace, embroidered tulle, trims and appliqués for gowns, veils and couture applications.", image:mediaUrl("luxury-beaded.jpg"), alt:"beaded bridal lace applique for wedding gown design" },
  { title:"Accessories & Craft", text:"Custom motifs and trims for bags, headpieces, gifts, seasonal products and creative accessories.", image:mediaUrl("pastel-assortment.jpg"), alt:"colorful embroidered lace motifs for accessories and creative products" },
];
const advantages = [
  { icon:Palette,title:"Multicolor Embroidery",text:"Develop coordinated thread palettes instead of being limited to white or single-color lace." },
  { icon:Lightbulb,title:"Custom Motif Development",text:"Develop motifs, dimensions, repeats and edge layouts from reference images or artwork." },
  { icon:Boxes,title:"Flexible Development",text:"Sampling and order solutions are reviewed according to design complexity and production method." },
  { icon:SwatchBook,title:"Seasonal & Fashion Focus",text:"Suitable for hair bows, childrenswear, seasonal collections, fashion trims and bridal applications." },
  { icon:BadgeCheck,title:"Sample Approval",text:"Color balance, stitch definition, motif scale and construction can be checked before bulk production." },
  { icon:Globe2,title:"International Service",text:"Responsive export communication, packing coordination and worldwide delivery options." },
];

export default function Home() { return <main>
<section className="loti-hero home-b2b-hero" id="home"><Image className="loti-hero-background" src="/images/about/about-hero.webp" alt="custom multicolor embroidered lace trim supplier China" width={1100} height={1100} priority sizes="100vw" /><span className="loti-hero-overlay" /><div className="loti-hero-content"><p className="loti-kicker">Custom Embroidery Development · China Sourcing</p><h1>Custom Multicolor Embroidered Lace <em>for Fashion &amp; Bridal Buyers.</em></h1><p>VELORACE LACE develops colorful embroidered lace trim from reference images and artwork. Build several thread colors into one motif and customize the motif scale, width, repeat, base and edge construction for hair bows, childrenswear, seasonal collections, fashion apparel and bridal projects.</p><div className="hero-actions"><WhatsAppLink className="button button-whatsapp" message={homeWhatsAppMessage} productCategory="Custom Multicolor Embroidered Lace" placement="homepage_hero_primary">Send your design on WhatsApp <ArrowRight size={17} /></WhatsAppLink><a className="button button-outline" href="/custom-multicolor-embroidered-lace">Explore multicolor customization <ArrowRight size={15} /></a></div><p className="whatsapp-cta-note">Send reference + colors + width + quantity + application → discuss sampling, MOQ and production route.</p></div></section>
<FeaturedHairBowLace />
<section className="loti-trust-strip">{trust.map(([value,label]) => <div key={value}><strong>{value}</strong><span>{label}</span></div>)}</section>
<section className="loti-section"><div className="loti-section-head"><div><p className="loti-kicker">Embroidered lace collections</p><h2>Multicolor embroidery first, with bridal and dimensional lace capabilities.</h2></div><p>Start with a colorful custom motif or browse existing lace directions, then send your target colors, dimensions and application for development.</p></div><div className="loti-trend-grid">{trends.map((item,index)=><a href={item.href} className="loti-trend-card" key={`${item.name}-${index}`}><Image src={item.image} alt={item.alt} width={900} height={900} sizes="(max-width: 900px) 50vw, 25vw" /><span>{String(index+1).padStart(2,"0")}</span><small>{item.type}</small><h3>{item.name}</h3></a>)}</div></section>
<section className="loti-split"><div className="loti-split-copy"><p className="loti-kicker">Custom lace supply capability</p><h2>One contact from color idea to embroidered sample.</h2><p>We coordinate suitable embroidery and lace production resources according to each design, color palette, technique and order requirement. Buyers receive one clear point of contact from reference review through sampling and delivery.</p><ul><li>Multicolor thread and motif development</li><li>Width, repeat and edge construction review</li><li>Physical sample approval before bulk</li><li>Export packing and logistics support</li></ul><p className="detail-note">Production arrangements vary by product, construction and order.</p><a className="text-link" href="/custom-multicolor-embroidered-lace">See multicolor embroidery capability <ArrowRight size={15} /></a></div><div className="loti-split-media"><Image src={mediaUrl("workshop-team.jpg")} alt="embroidery inspection finishing and lace material workflow" width={1000} height={1100} sizes="(max-width: 900px) 100vw, 50vw" /></div></section>
<section className="loti-section loti-process"><div className="loti-section-head"><div><p className="loti-kicker">Custom development process</p><h2>From reference image to approved embroidery.</h2></div><p>A clear approval workflow helps protect color, motif scale, construction and repeat-order consistency.</p></div><div className="loti-process-grid">{manufacturingProcess.map(([num,title,Icon,text])=><article key={title}><span>{num}</span><Icon size={26}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="loti-section"><div className="loti-section-head"><div><p className="loti-kicker">Applications</p><h2>Color and construction developed around the final product.</h2></div><p>Share the intended application so motif size, repeat, thread palette and base can be evaluated together.</p></div><div className="loti-application-grid">{applications.map((item)=><article key={item.title}><Image src={item.image} alt={item.alt} width={900} height={700} sizes="(max-width: 900px) 100vw, 25vw"/><div><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div></section>
<section className="loti-split loti-split-reverse"><div className="loti-split-media"><Image src={mediaUrl("sample-review.jpg")} alt="custom embroidered lace development reference" width={1000} height={1100} sizes="(max-width: 900px) 100vw, 50vw" /></div><div className="loti-split-copy"><p className="loti-kicker">Multicolor custom development</p><h2>Turn your color palette and motif into embroidered lace.</h2><p>Send artwork, a product photo or physical sample. We help evaluate the practical construction and develop thread colors, motif scale, width, repeat, base and decorative finish for your application.</p><ul><li>Multiple thread colors in one motif</li><li>Motif scale and repeat adjustment</li><li>Pantone or swatch-based color discussion</li><li>Physical sample approval before production</li></ul><WhatsAppLink className="button button-dark" message={homeWhatsAppMessage} productCategory="Custom Multicolor Embroidered Lace" placement="homepage_custom_development">Discuss your design <ArrowRight size={16}/></WhatsAppLink></div></section>
<section className="loti-section"><div className="loti-section-head"><div><p className="loti-kicker">Why VELORACE</p><h2>A focused partner for custom colorful embroidery.</h2></div><p>Practical development support for buyers who need distinctive multicolor lace rather than only standard catalog designs.</p></div><div className="loti-advantage-grid">{advantages.map(({icon:Icon,title,text})=><article key={title}><Icon size={25}/><h3>{title}</h3><p>{text}</p></article>)}</div><div className="loti-about-link"><a className="text-link" href="/about">About VELORACE LACE <ArrowRight size={15}/></a></div></section>
<section className="loti-section home-faq"><div className="loti-section-head"><div><p className="loti-kicker">Buyer answers</p><h2>What to send before developing multicolor embroidered lace.</h2></div><p>A reference image is the best starting point. We confirm the practical development route after reviewing colors, motif, construction, dimensions, quantity and application.</p></div><div className="home-faq-grid"><article><h3>Can one design use several colors?</h3><p>Yes. Send the desired palette or reference. The practical thread-color count and stitch plan are reviewed during development.</p></article><article><h3>Can you develop from my picture?</h3><p>Send artwork, a product photo or concept together with the target application, width and approximate motif size.</p></article><article><h3>What is the MOQ?</h3><p>MOQ varies by design, construction and production method. We confirm it after reviewing the actual project rather than publishing an unsupported generic number.</p></article><article><h3>Can I approve a sample first?</h3><p>Yes. Sampling is recommended for custom multicolor designs so color balance, stitch definition, scale and hand feel can be checked before bulk.</p></article></div></section>
<section className="loti-quote"><div><p className="loti-kicker">Custom embroidery inquiry</p><h2>Send your colors &amp; motif.<br/>Develop the lace.</h2><p>Share the reference, colors, width, quantity, application and destination. We will review the suitable sampling and production route.</p><ul><li>Multicolor embroidered lace trim</li><li>Seasonal and custom motif development</li><li>Bridal and fashion lace sourcing</li></ul></div><QuoteForm /></section>
</main>; }
