import Image from "next/image";
import { ArrowRight, BadgeCheck, MessageCircle } from "lucide-react";
import QuoteForm from "@/components/QuoteForm";
import type { ProductData } from "@/lib/products";

export default function ProductDetail({ product }: { product: ProductData }) {
  const whatsappMessage = encodeURIComponent(`Hello VELORACE LACE, I’m interested in the ${product.name}, SKU ${product.sku}.\n\nRequired quantity:\nRequired color:\nDestination country:\nTarget delivery date:\n\nPlease send me the sample and wholesale quotation details.\n\nProduct page: https://www.veloracelace.com/products/${product.slug}`);
  const whatsappUrl = `https://wa.me/8615767956637?text=${whatsappMessage}`;
  return <main className="product-page">
    <section className="product-hero">
      <div className="product-hero-media"><Image src={product.image} alt={product.imageAlt} width={1122} height={1402} priority sizes="(max-width: 900px) 100vw, 52vw" /><p>{product.conceptNote}</p></div>
      <div className="product-hero-copy"><nav className="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href="/products">Products</a><span>/</span><a href="/bridal-lace">Bridal Lace</a></nav><p className="eyebrow"><span /> SKU {product.sku}</p><h1>{product.name}</h1><p className="product-lead">{product.description}</p><div className="product-buying-grid">{product.buyingInfo.map((item) => <div key={item.label}><span>{item.label}</span><strong>{item.value}</strong></div>)}</div><div className="hero-actions"><a className="button button-dark" href="#product-inquiry">Request a Wholesale Quote <ArrowRight size={16} /></a><a className="button button-outline" href={whatsappUrl} target="_blank" rel="noreferrer">Chat on WhatsApp <MessageCircle size={16} /></a><a className="text-link" href="#product-inquiry">Request a Custom Sample <ArrowRight size={15} /></a></div></div>
    </section>
    <section className="section product-highlights"><div className="section-heading split-heading"><div><p className="eyebrow"><span /> Product highlights</p><h2>Dimensional detail for couture placement.</h2></div><p>{product.fullName}, developed around the final garment and approved sample.</p></div><div className="product-check-grid">{product.highlights.map((item) => <p key={item}><BadgeCheck size={18} />{item}</p>)}</div></section>
    <section className="section product-spec-section"><div className="section-heading split-heading"><div><p className="eyebrow"><span /> Technical specifications</p><h2>Clear details for sourcing.</h2></div><p>Measurements are approximate. Final specifications are confirmed during sample development.</p></div><dl className="product-spec-table">{product.specifications.map((item) => <div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl></section>
    <section className="section product-two-column"><div><p className="eyebrow"><span /> Applications</p><h2>Designed for bridal and statement garments.</h2><ul>{product.applications.map((item) => <li key={item}><BadgeCheck size={17} />{item}</li>)}</ul></div><div><p className="eyebrow"><span /> Custom development available</p><h2>Shape the detail around your collection.</h2><ul>{product.customization.map((item) => <li key={item}><BadgeCheck size={17} />{item}</li>)}</ul><p className="product-disclaimer">Final MOQ, sample cost and production time are confirmed after reviewing the required size, workmanship and order quantity.</p></div></section>
    <section className="section product-process"><div className="section-heading centered-heading"><p className="eyebrow"><span /> Purchasing process</p><h2>From requirement to worldwide delivery.</h2></div><div>{product.process.map((item, index) => <article key={item}><span>{String(index + 1).padStart(2, "0")}</span><h3>{item}</h3></article>)}</div></section>
    <section className="section faq-section product-faq"><div className="section-heading"><p className="eyebrow"><span /> FAQ</p><h2>Common questions about {product.sku}.</h2></div><div className="faq-list">{product.faqs.map((faq) => <details key={faq.question}><summary>{faq.question}<span>+</span></summary><p>{faq.answer}</p></details>)}</div></section>
    <section className="quote-section" id="product-inquiry"><div className="quote-intro"><p className="eyebrow eyebrow-light"><span /> Wholesale inquiry</p><h2>Request your sample<br />and quotation.</h2><p>Tell us the quantity, color, destination and delivery target for {product.sku}. We will confirm the suitable sampling and production route.</p><ul><li><BadgeCheck size={17} /> Product and SKU included automatically</li><li><BadgeCheck size={17} /> Current page URL included</li><li><BadgeCheck size={17} /> WhatsApp fallback available</li></ul></div><QuoteForm productName={product.name} sku={product.sku} /></section>
  </main>;
}
