export const hairBowPath = "/hair-bow-lace";
export type HairBowDesign = { slug: string; name: string; theme: string; description: string; use: string; development: string; image?: string; alt: string };
const designs = [
  ["pink-christmas-tree-gift-bow", "Pink Christmas Tree + Gift + Bow", "Christmas", "Pink Christmas trees, gifts and bows create a soft holiday motif direction for embroidered tulle lace trim.", "Christmas boutique bows, holiday hair clips and coordinated gift accessories", "Review the tree and gift scale against the ribbon width so the main motifs remain visible on the bow loops."],
  ["gingerbread-candy-cane-bow", "Gingerbread + Candy Cane + Bow", "Christmas", "Gingerbread figures, candy canes and bows form a playful Christmas embroidery concept for narrow lace ribbon.", "Gingerbread themed hair bows and candy themed holiday accessories", "Check candy cane stripe detail and gingerbread features in a physical sample at the requested finished width."],
  ["santa-christmas-tree-gift", "Santa + Christmas Tree + Gift", "Christmas", "Santa, Christmas trees and gifts define this festive embroidered lace trim concept for bow makers.", "Santa themed boutique bows and Christmas outfit accessories", "Position the Santa motif away from the center wrap and confirm facial detail during sample review."],
  ["ghost-pumpkin-pink-bow", "Ghost + Pumpkin + Pink Bow", "Halloween", "Ghosts, pumpkins and pink bows combine in a Halloween tulle lace concept for children's hair accessories.", "Halloween hair bows, pumpkin patch outfit accessories and seasonal hair clips", "Review contrast between the ghost thread, mesh base and underlying ribbon before approving the sample."],
  ["apple-pencil-bow", "Apple + Pencil + Bow", "Back to school", "Apples, pencils and bows provide a classroom inspired motif direction for custom embroidered lace ribbon.", "First day of school bows and classroom themed hair accessories", "Confirm pencil length and repeat spacing around the intended bow folds."],
  ["books-apple-school-bow", "Books + Apple + School Bow", "Back to school", "Books, apples and school bows create a reading and classroom embroidery concept on narrow tulle trim.", "Reading themed boutique bows and back to school accessory collections", "Discuss school color references and keep book details legible at the sample scale."],
  ["pink-cross-bow-floral", "Pink Cross + Bow + Floral", "Cross & floral", "A pink cross, bows and floral motifs define this decorative embroidered tulle lace concept.", "Faith themed hair bows and coordinated occasion accessories", "Review cross placement and floral spacing so the motif is visible on the finished bow loops."],
  ["white-cross-blue-bow-floral", "White Cross + Blue Bow + Floral", "Cross & floral", "White crosses, blue bows and floral motifs offer a contrasting cross themed lace overlay concept.", "Blue and white occasion bows and faith themed hair accessories", "Sample the white cross against the selected ribbon color and confirm the blue thread reference."],
  ["ballerina-girl-bow-heart", "Ballerina Girl + Bow + Heart", "Ballet", "Ballerina girls, bows and hearts create a ballet inspired embroidered lace development concept.", "Ballet themed boutique hair bows and dance outfit accessories", "Review figure detail and motif height in the sample before choosing the final repeat length."],
  ["teddy-bear-bow-heart", "Teddy Bear + Bow + Heart", "Everyday", "Teddy bears, bows and hearts form an everyday embroidered tulle lace concept for bow collections.", "Teddy themed hair bows, birthday outfit accessories and everyday boutique clips", "Confirm bear features and thread contrast on the intended ribbon backing."],
  ["bunny-bow-heart", "Bunny + Bow + Heart", "Spring", "Bunnies, bows and hearts define a spring inspired custom lace trim concept for hair bow development.", "Bunny themed boutique bows and spring hair accessory collections", "Check the bunny ear height against the finished lace width and bow folds."],
  ["cherry-bow-heart", "Cherry + Bow + Heart", "Everyday", "Cherries, bows and hearts create a fruit themed embroidered lace ribbon concept with a coquette influence.", "Cherry themed hair bows, summer accessories and coquette boutique collections", "Review cherry stem detail and spacing between hearts and bows in the physical sample."],
] as const;
export const hairBowDesigns: HairBowDesign[] = designs.map(([slug, name, theme, description, use, development]) => {
  const productSlug = `${slug}-embroidered-lace-trim`;
  return { slug: productSlug, name, theme, description, use, development, image: `/products/hair-bow-lace/${productSlug}.webp`, alt: `Design concept for ${name.toLowerCase()} embroidered tulle lace trim for children's hair bows` };
});
export const hairBowUrl = (design: HairBowDesign) => `${hairBowPath}/${design.slug}`;
export const conceptNotice = "Design concepts for development, not factory photographs, QC photographs or customer orders. Final construction, color and dimensions are subject to physical sample approval.";
export const orderingAnswer = "Send the design name, requested finished width, thread colors, estimated length in yards or meters and US delivery ZIP code. MOQ, price, sample time, bulk lead time, packing and shipping are confirmed after design review.";
export function designFaq(design: HairBowDesign) { return [
  { q: `What is ${design.name} hair bow lace?`, a: `${design.description} It is a trim development concept from VELORACE LACE, not a finished hair bow or an in-stock product promise.` },
  { q: "How is it used for children's hair bows?", a: `Use it as a decorative overlay on ribbon for ${design.use.toLowerCase()}. Align a visible motif with each loop, check the center wrap placement and test attachment on a physical sample before production.` },
  { q: "Is the lace 1.5 inches wide?", a: "The development target is approximately 1.5 inches (38.1 mm). Confirm the actual finished width and edge fit with your ribbon during sample review; a concept image does not establish a measured specification." },
  { q: "Can I customize this design?", a: `${design.development} Motif scale, repeat spacing, thread colors, mesh base, edge finish and requested width can be reviewed for feasibility.` },
  { q: "How do sampling and ordering work?", a: orderingAnswer + " Agree the sample scope first, review the physical sample, then confirm the bulk order against the approved specification." },
]; }
