import type { Metadata } from "next";
import Link from "next/link";

const path = "/seasonal-embroidered-lace-trim";
const base = "https://www.veloracelace.com";
const whatsapp = "https://wa.me/8615767956637?text=Hello%20VELORACE%20LACE%2C%20I%20am%20developing%20a%20seasonal%20multicolor%20embroidered%20lace%20trim.%20I%20will%20send%20the%20theme%2C%20reference%2C%20colors%2C%20width%2C%20application%20and%20quantity.";
export const metadata: Metadata = { title: "Seasonal Multicolor Embroidered Lace Trim | Custom Supplier", description: "Develop custom Christmas, Halloween, back-to-school and Valentine's multicolor embroidered lace trim from artwork or reference images for fashion and hair accessories.", alternates: { canonical: path }, openGraph: { title: "Seasonal Multicolor Embroidered Lace Trim | VELORACE LACE", description: "Custom seasonal embroidery motifs and coordinated thread colors for narrow lace trim, hair bows, childrenswear and fashion accessories.", url: path, type: "website" } };
const themes = [["Christmas embroidery", "Christmas trees, gifts, bows, candy canes, gingerbread and other recognizable holiday motifs can be developed as repeating multicolor trim directions."],["Halloween embroidery", "Ghost, pumpkin, bow and other Halloween directions can combine a limited coordinated palette with motifs sized for the intended trim width."],["Back-to-school embroidery", "Apple, pencil, book, school-bow and related motifs can be developed for children's accessories and seasonal boutique collections."],["Valentine's embroidery", "Heart, bow, floral and other Valentine's directions can be developed around the buyer's palette, target width and finished-product application."]] as const;
const faqs = [["Can seasonal lace use several embroidery colors?", "Yes. Multicolor thread palettes can be reviewed as part of the design. Send the intended colors and reference artwork so the practical embroidery construction can be evaluated before sampling."],["Can you develop a seasonal motif from my own artwork?", "Yes. Send the artwork or reference together with the application, target width, approximate motif scale and color direction for development review."],["Is seasonal embroidered lace suitable for hair bows?", "It can be developed for hair-bow overlays and other children's accessories when the motif repeat, trim width and center-fold visibility are planned around the finished bow."],["Should I order a sample first?", "A physical sample is recommended for a custom seasonal design so color balance, motif readability, stitch definition, repeat and fit can be reviewed before bulk production."]] as const;
export default function SeasonalLacePage() {
  const schema = [{ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: base }, { "@type": "ListItem", position: 2, name: "Custom Multicolor Embroidered Lace", item: `${base}/custom-multicolor-embroidered-lace` }, { "@type": "ListItem", position: 3, name: "Seasonal Embroidered Lace Trim", item: `${base}${path}` }] }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([q,a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) }];
  return <main className="mx-auto max-w-6xl px-5 py-10 md:py-16">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <nav className="mb-6 text-sm text-neutral-600"><Link href="/">Home</Link> / <Link href="/custom-multicolor-embroidered-lace">Multicolor Embroidery</Link> / Seasonal Lace</nav>
    <section className="max-w-4xl"><p className="mb-3 text-sm font-semibold uppercase tracking-wider">Seasonal motif development · Custom multicolor embroidery</p><h1 className="text-4xl font-semibold leading-tight md:text-6xl">Seasonal Multicolor Embroidered Lace Trim</h1><p className="mt-6 text-lg leading-8 text-neutral-700">Develop Christmas, Halloween, back-to-school, Valentine&apos;s and other seasonal embroidered lace trims around your own color palette and finished product. VELORACE LACE can review artwork, motif scale, thread colors, repeat spacing, target width, mesh base and edge construction before a physical sample is approved.</p><div className="mt-7 flex flex-wrap gap-3"><a className="rounded-full bg-black px-6 py-3 text-white" href={whatsapp}>Send your seasonal design</a><Link className="rounded-full border border-neutral-300 px-6 py-3" href="/hair-bow-lace">View hair bow concepts</Link></div></section>
    <section className="mt-16"><h2 className="text-3xl font-semibold">Seasonal embroidery directions</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{themes.map(([h,p]) => <article className="rounded-2xl border border-neutral-200 p-6" key={h}><h3 className="text-xl font-semibold">{h}</h3><p className="mt-3 leading-7 text-neutral-700">{p}</p></article>)}</div></section>
    <section className="mt-16 rounded-2xl bg-neutral-100 p-7 md:p-10"><h2 className="text-3xl font-semibold">Design the motif for the finished product</h2><p className="mt-4 max-w-4xl leading-7 text-neutral-700">Seasonal embroidery works best when the motif is planned for the actual application rather than treated as isolated artwork. A hair-bow trim may need a compact repeat that remains visible after folding; a garment edge may need a different scale and spacing. Send the finished-product dimensions or application reference together with the artwork so the sample can be reviewed in context.</p></section>
    <section className="mt-16 grid gap-6 md:grid-cols-3"><article className="rounded-2xl border border-neutral-200 p-6"><h2 className="text-xl font-semibold">1. Theme & artwork</h2><p className="mt-3 leading-7 text-neutral-700">Send the holiday or seasonal direction, artwork, reference image and motifs that must remain recognizable.</p></article><article className="rounded-2xl border border-neutral-200 p-6"><h2 className="text-xl font-semibold">2. Color & layout</h2><p className="mt-3 leading-7 text-neutral-700">Define the target palette, width, motif scale and repeat. Keep the palette purposeful when production simplicity matters.</p></article><article className="rounded-2xl border border-neutral-200 p-6"><h2 className="text-xl font-semibold">3. Physical sample</h2><p className="mt-3 leading-7 text-neutral-700">Review stitch definition, color balance, repeat, hand feel and fit on the intended product before bulk confirmation.</p></article></section>
    <section className="mt-16"><h2 className="text-3xl font-semibold">Related custom embroidery sourcing</h2><p className="mt-4 leading-7 text-neutral-700">For a broader custom program, start with <Link className="font-semibold underline" href="/custom-multicolor-embroidered-lace">custom multicolor embroidered lace trim</Link>. For children&apos;s boutique bow applications, browse the <Link className="font-semibold underline" href="/hair-bow-lace">hair bow lace collection</Link>. For general embroidery constructions, see <Link className="font-semibold underline" href="/embroidery-lace">embroidery lace</Link>.</p></section>
    <section className="mt-16"><h2 className="text-3xl font-semibold">Seasonal embroidered lace FAQ</h2><div className="mt-6 divide-y">{faqs.map(([q,a]) => <div className="py-5" key={q}><h3 className="text-xl font-semibold">{q}</h3><p className="mt-2 leading-7 text-neutral-700">{a}</p></div>)}</div></section>
    <section className="mt-16 rounded-2xl bg-black p-8 text-white md:p-10"><h2 className="text-3xl font-semibold">Develop a seasonal lace trim around your market.</h2><p className="mt-4 max-w-3xl leading-7 text-neutral-200">Send the theme, reference image, colors, target width, application, estimated quantity and destination. Sampling and commercial specifications can then be discussed for that design.</p><a className="mt-6 inline-block rounded-full bg-white px-6 py-3 font-semibold text-black" href={whatsapp}>Send seasonal reference on WhatsApp</a></section>
  </main>;
}
